version: '3.7'

services:

  frontend-dev:
    image: def/desafio-frontend:dev
    container_name: desafio-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3003:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL='seu valor aqui'

  frontend-prod:
    image: desafio-frontend:prod
    container_name: desafio-frontend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'